#############################################################################
# Makefile for building: rtqt
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 3? 6 13:44:27 2018
# Project:  rtqt.pro
# Template: app
# Command: c:/msys64/mingw32/bin/qmake.exe -o Makefile rtqt.pro
#############################################################################

first: debug
install: debug-install
uninstall: debug-uninstall
MAKEFILE      = Makefile
QMAKE         = c:/msys64/mingw32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = cp -rf
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		debug \
		release

debug: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_default: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-make_first: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug first
debug-all: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: $(MAKEFILE).Debug FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall
release: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_default: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-make_first: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release first
release-all: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: $(MAKEFILE).Release FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall

Makefile: rtqt.pro  ../../../msys64/mingw32/share/qt4/mkspecs/default/qmake.conf ../../../msys64/mingw32/share/qt4/mkspecs/qdevice.pri \
		../../../msys64/mingw32/share/qt4/mkspecs/features/device_config.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/qconfig.pri \
		../../../msys64/mingw32/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		../../../msys64/mingw32/share/qt4/mkspecs/features/qt_functions.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/qt_config.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/win32-g++/qmake.conf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/default_pre.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/default_pre.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/debug.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/debug_and_release.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/default_post.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/default_post.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/stl.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/rtti.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/exceptions.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/shared.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/warn_on.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/qt.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/thread.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/moc.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/windows.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/resources.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/uic.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/yacc.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/lex.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/include_source_dir.prf \
		c:/msys64/mingw32/lib/qtmaind.prl
	$(QMAKE) -o Makefile rtqt.pro
../../../msys64/mingw32/share/qt4/mkspecs/qdevice.pri:
../../../msys64/mingw32/share/qt4/mkspecs/features/device_config.prf:
../../../msys64/mingw32/share/qt4/mkspecs/qconfig.pri:
../../../msys64/mingw32/share/qt4/mkspecs/modules/qt_webkit_version.pri:
../../../msys64/mingw32/share/qt4/mkspecs/features/qt_functions.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/qt_config.prf:
../../../msys64/mingw32/share/qt4/mkspecs/win32-g++/qmake.conf:
../../../msys64/mingw32/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/default_pre.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/default_pre.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/debug.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/debug_and_release.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/default_post.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/default_post.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/stl.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/rtti.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/exceptions.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/shared.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/warn_on.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/qt.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/thread.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/moc.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/windows.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/resources.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/uic.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/yacc.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/lex.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/include_source_dir.prf:
c:\msys64\mingw32\lib\qtmaind.prl:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile rtqt.pro

qmake_all: FORCE

make_default: debug-make_default release-make_default FORCE
make_first: debug-make_first release-make_first FORCE
all: debug-all release-all FORCE
clean: debug-clean release-clean FORCE
distclean: debug-distclean release-distclean FORCE
	-$(DEL_FILE) Makefile

check: first

debug-mocclean: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocclean
release-mocclean: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocclean
mocclean: debug-mocclean release-mocclean

debug-mocables: $(MAKEFILE).Debug
	$(MAKE) -f $(MAKEFILE).Debug mocables
release-mocables: $(MAKEFILE).Release
	$(MAKE) -f $(MAKEFILE).Release mocables
mocables: debug-mocables release-mocables
FORCE:

$(MAKEFILE).Debug: Makefile
$(MAKEFILE).Release: Makefile
