#############################################################################
# Makefile for building: rtqt
# Generated by qmake (2.01a) (Qt 4.8.7) on: ?? 3? 16 15:20:05 2018
# Project:  rtqt.pro
# Template: subdirs
# Command: c:/msys64/mingw32/bin/qmake.exe -o Makefile rtqt.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = c:/msys64/mingw32/bin/qmake.exe
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = cp -rf
INSTALL_FILE  = $(COPY_FILE)
INSTALL_PROGRAM = $(COPY_FILE)
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = 
DEL_DIR       = rmdir
MOVE          = mv
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-build \
		sub-test

build/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) build/ || $(MKDIR) build/ 
	cd build/ && $(QMAKE) c:/Home/Code/rtqt/build/build.pro -o $(MAKEFILE)
sub-build-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) build/ || $(MKDIR) build/ 
	cd build/ && $(QMAKE) c:/Home/Code/rtqt/build/build.pro -o $(MAKEFILE)
sub-build: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE)
sub-build-make_default-ordered: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) 
sub-build-make_default: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) 
sub-build-make_first-ordered: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) first
sub-build-make_first: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) first
sub-build-all-ordered: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) all
sub-build-all: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) all
sub-build-clean-ordered: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) clean
sub-build-clean: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) clean
sub-build-distclean-ordered: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) distclean
sub-build-distclean: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) distclean
sub-build-install_subtargets-ordered: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) install
sub-build-install_subtargets: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) install
sub-build-uninstall_subtargets-ordered: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-build-uninstall_subtargets: build/$(MAKEFILE) FORCE
	cd build/ && $(MAKE) -f $(MAKEFILE) uninstall
test/$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) test/ || $(MKDIR) test/ 
	cd test/ && $(QMAKE) c:/Home/Code/rtqt/test/test.pro -o $(MAKEFILE)
sub-test-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) test/ || $(MKDIR) test/ 
	cd test/ && $(QMAKE) c:/Home/Code/rtqt/test/test.pro -o $(MAKEFILE)
sub-test: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE)
sub-test-make_default-ordered: test/$(MAKEFILE) sub-build-make_default-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) 
sub-test-make_default: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) 
sub-test-make_first-ordered: test/$(MAKEFILE) sub-build-make_first-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) first
sub-test-make_first: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) first
sub-test-all-ordered: test/$(MAKEFILE) sub-build-all-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) all
sub-test-all: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) all
sub-test-clean-ordered: test/$(MAKEFILE) sub-build-clean-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) clean
sub-test-clean: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) clean
sub-test-distclean-ordered: test/$(MAKEFILE) sub-build-distclean-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) distclean
sub-test-distclean: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) distclean
sub-test-install_subtargets-ordered: test/$(MAKEFILE) sub-build-install_subtargets-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) install
sub-test-install_subtargets: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) install
sub-test-uninstall_subtargets-ordered: test/$(MAKEFILE) sub-build-uninstall_subtargets-ordered  FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) uninstall
sub-test-uninstall_subtargets: test/$(MAKEFILE) FORCE
	cd test/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: rtqt.pro  ../../../msys64/mingw32/share/qt4/mkspecs/default/qmake.conf ../../../msys64/mingw32/share/qt4/mkspecs/qdevice.pri \
		../../../msys64/mingw32/share/qt4/mkspecs/features/device_config.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/qconfig.pri \
		../../../msys64/mingw32/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		../../../msys64/mingw32/share/qt4/mkspecs/features/qt_functions.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/qt_config.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/win32-g++/qmake.conf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/exclusive_builds.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/default_pre.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/default_pre.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/debug.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/debug_and_release.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/default_post.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/default_post.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/stl.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/rtti.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/exceptions.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/shared.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/warn_on.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/qt.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/thread.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/moc.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/win32/windows.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/resources.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/uic.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/yacc.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/lex.prf \
		../../../msys64/mingw32/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile rtqt.pro
../../../msys64/mingw32/share/qt4/mkspecs/qdevice.pri:
../../../msys64/mingw32/share/qt4/mkspecs/features/device_config.prf:
../../../msys64/mingw32/share/qt4/mkspecs/qconfig.pri:
../../../msys64/mingw32/share/qt4/mkspecs/modules/qt_webkit_version.pri:
../../../msys64/mingw32/share/qt4/mkspecs/features/qt_functions.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/qt_config.prf:
../../../msys64/mingw32/share/qt4/mkspecs/win32-g++/qmake.conf:
../../../msys64/mingw32/share/qt4/mkspecs/features/exclusive_builds.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/default_pre.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/default_pre.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/debug.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/debug_and_release.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/default_post.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/default_post.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/stl.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/rtti.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/exceptions.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/shared.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/warn_on.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/qt.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/thread.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/moc.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/win32/windows.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/resources.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/uic.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/yacc.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/lex.prf:
../../../msys64/mingw32/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -o Makefile rtqt.pro

qmake_all: sub-build-qmake_all sub-test-qmake_all FORCE

make_default: sub-build-make_default-ordered sub-test-make_default-ordered FORCE
make_first: sub-build-make_first-ordered sub-test-make_first-ordered FORCE
all: sub-build-all-ordered sub-test-all-ordered FORCE
clean: sub-build-clean-ordered sub-test-clean-ordered FORCE
distclean: sub-build-distclean-ordered sub-test-distclean-ordered FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-build-install_subtargets-ordered sub-test-install_subtargets-ordered FORCE
uninstall_subtargets: sub-build-uninstall_subtargets-ordered sub-test-uninstall_subtargets-ordered FORCE

sub-build-sub_Debug_ordered: build/$(MAKEFILE)
	cd build/ && $(MAKE) -f $(MAKEFILE) debug
sub-test-sub_Debug_ordered: test/$(MAKEFILE) sub-build-sub_Debug_ordered 
	cd test/ && $(MAKE) -f $(MAKEFILE) debug
debug: sub-build-sub_Debug_ordered sub-test-sub_Debug_ordered

sub-build-sub_Release_ordered: build/$(MAKEFILE)
	cd build/ && $(MAKE) -f $(MAKEFILE) release
sub-test-sub_Release_ordered: test/$(MAKEFILE) sub-build-sub_Release_ordered 
	cd test/ && $(MAKE) -f $(MAKEFILE) release
release: sub-build-sub_Release_ordered sub-test-sub_Release_ordered

sub-build-check_ordered: build/$(MAKEFILE)
	cd build/ && $(MAKE) -f $(MAKEFILE) check
sub-test-check_ordered: test/$(MAKEFILE) sub-build-check_ordered 
	cd test/ && $(MAKE) -f $(MAKEFILE) check
check: sub-build-check_ordered sub-test-check_ordered

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

