######################################################################
# Automatically generated by qmake (2.01a) ?? 3? 2 16:37:33 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . debug
INCLUDEPATH += .

# Input
HEADERS += mainwindow.hpp
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
RESOURCES += rtqt.qrc
